version: '3.8'

services:
  liveme_django:
    build:
      context: ./liveme_django
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./liveme_django/:/usr/src/liveme_django/
    ports:
      - 8000:8000
    env_file:
      - ./liveme_django/welive/.env
    depends_on:
      - db
    environment:
      - SQL_DATABASE=liveme
      - SQL_USER=admin
      - SQL_PASSWORD=NaliPK,nalinaL

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=NaliPK,nalinaL
      - POSTGRES_DB=liveme

  liveme_next:
    build:
      context: ./liveme_next
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - liveme_django
      - liveme_next

volumes:
  postgres_data:


