version: '3.8'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn welive.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./django/welive/.prod.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 3000:3000
    depends_on:
      - web

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=liveme
volumes:
  postgres_data:
  static_volume:


