version: '3.8'

services:
  liveme_django:
    build:
      context: ./liveme_django
      dockerfile: Dockerfile.prod
    command: gunicorn welive.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/liveme_django/staticfiles
    expose:
      - 8000
    env_file:
      - ./liveme_django/welive/.env
    depends_on:
      - db
    environment:
      - SQL_DATABASE=liveme
      - SQL_USER=admin
      - SQL_PASSWORD=NaliPK,nalinaL


  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:

      - liveme_next
    restart: always
    
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=NaliPK,nalinaL
      - POSTGRES_DB=liveme
    restart: always

  liveme_next:
    build: ./liveme_next
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres_data:
  static_volume:


