# Generated by Django 4.1.1 on 2022-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_client_address_order_client_email_and_more'),
        ('users', '0004_rename_adress_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='orders',
            field=models.ManyToManyField(blank=True, to='orders.order'),
        ),
    ]
